### ISSUE TITLE
data exceeding MAX_FRAGMENT_LENGTH

### ISSUE THREAD

**Issue by cnudroid** [mobius-software-ltd/java-dtls#5]
If we want to send data which is large than MAX_FRAGMENT_LENGTH, how should we implement?

Should we break down into fragments and construct them back on the server?

**Comment by yulianoifa-mobius** [comment]
Hi @cnudroid 
Yes you would need to split the data out. Otherwise you would receive TLS Exception. In case you are reusing the test dtls client it may be done by rewriting the sendPacket method. It may just split the buffer into multiple buffers based on MAX_FRAGMENT_LENGTH and send then sequentially.
On Server side you would need to construct the data in any case , even if client code would be changed on Dtls layer
